import "./workshop-final.css";

const whatsapp = "https://wa.me/5217713653473?text=Hola%2C%20quiero%20recibir%20informaci%C3%B3n%20para%20inscribirme%20al%20Workshop%20Intensivo%20de%20Inteligencia%20Artificial%20para%20Asesores%20Inmobiliarios.";
const pillars = [["P","Prospectar","Ordena la información de una propiedad y detecta vacíos."],["R","Relacionar","Convierte consultas en conversaciones claras y humanas."],["O","Optimizar","Crea contenido y procesos sin comenzar desde cero."],["P","Presentar","Presenta con claridad para ayudar a decidir y avanzar."]];
const builds = ["Diagnóstico Comercial P.R.O.P. de una propiedad real.","Perfil de comprador y ángulo comercial definido.","Mensajes de WhatsApp que abren conversaciones.","Landing v1, contenido y Brief Visual.","Presentación comercial y plan de 7 días."];
export default function Home(){return <main className="workshop">
  <div className="ribbon">WORKSHOP INTENSIVO <span>✦</span> IMPLEMENTACIÓN REAL <span>✦</span> PRIMERA GENERACIÓN FUNDADORA</div>
  <section className="whero" id="inicio"><nav className="wnav shell"><a className="wbrand" href="#inicio">MÉTODO <b>P.R.O.P.</b></a><span>UNA INICIATIVA DE LFMS BIENES RAÍCES</span><a href="#inscripcion">INSCRIBIRME <b>↗</b></a></nav><div className="wheroGrid shell"><div><p className="kicker">SISTEMA DE IMPLEMENTACIÓN PARA ASESORES INMOBILIARIOS</p><h1>WORKSHOP<br/><em>INTENSIVO</em><small>IA PARA ASESORES<br/>INMOBILIARIOS</small></h1><p className="lead">Convierte Inteligencia Artificial en un sistema comercial que puedes aplicar a tus propiedades.</p><div className="heroProof"><span>IMPLEMENTA IA EN TU OPERACIÓN</span><span>AHORRA TIEMPO, GENERA MÁS OPORTUNIDADES</span><span>DECIDE CON ESTRATEGIA</span></div><div className="heroActions"><a href="#inscripcion">INSCRIBIRME AHORA <b>↗</b></a><strong>$999 <small>MXN</small></strong></div></div><div className="wheroArt"><img src="/hero-prop-transformacion.png" alt="El proceso de transformar información inmobiliaria en un sistema comercial"/><i>MÉTODO<br/>P.R.O.P.</i></div></div></section>
  <section className="build shell" id="resultados"><div className="buildCopy"><p className="kicker dark">LO QUE CONSTRUIRÁS</p><h2>Tu sistema de IA<br/><em>aplicado</em> a tu negocio.</h2><p>No vienes a acumular prompts. Trabajas una propiedad real y sales con un sistema que puedes repetir en tu cartera.</p><ol>{builds.map((x,i)=><li key={x}><span>●</span>{x}</li>)}</ol></div><div className="dashboard" aria-label="Panel de control del sistema comercial"><div className="dashTitle">PANEL DE CONTROL IA <span>●</span></div><div className="metrics"><div><small>PROPIEDADES</small><b>128</b><em>+12%</em></div><div><small>OPORTUNIDADES</small><b>34</b><em>+8%</em></div><div><small>CONVERSIONES</small><b>21</b><em>+24%</em></div><div><small>AHORRO DE TIEMPO</small><b>16h</b><em>+30%</em></div></div><div className="dashBody"><div className="funnel"><span>EMBUDO DE OPORTUNIDADES</span><i/><i/><i/><i/></div><div className="chart"><span>RENDIMIENTO DE CONTENIDO</span><svg viewBox="0 0 240 100" aria-hidden="true"><polyline points="0,82 32,69 66,74 100,41 130,55 170,28 208,38 240,12"/></svg></div></div><div className="dashTasks"><span>✓ Generación de descripciones</span><span>✓ Análisis comparativo</span><span>✓ Guiones de seguimiento</span></div></div></section>
  <section className="method" id="metodo"><div className="shell"><p className="kicker">MÉTODO P.R.O.P.</p><h2>Una propiedad.<br/>Cuatro decisiones.</h2><div className="pillars">{pillars.map(([letter,title,text],i)=><article key={title}><span>0{i+1}</span><b>{letter}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="sessions shell"><div><p className="kicker dark">ARQUITECTURA DEL WORKSHOP</p><h2>Dos sesiones.<br/><em>Un método.</em></h2><p>Aprendizaje aplicado para convertir claridad comercial en acción.</p></div><div className="sessionCards"><article><span>SESIÓN 01</span><h3>Prospectar y relacionarte con IA</h3><p>Diagnóstico P.R.O.P. · comprador prioritario · mensajes y seguimiento.</p></article><article><span>SESIÓN 02</span><h3>Optimizar, presentar y avanzar</h3><p>Contenido · landing v1 · Brief Visual · presentación y plan de 7 días.</p></article></div></section>
  <section className="enroll" id="inscripcion"><div className="shell enrollGrid"><div><p className="kicker">PRIMERA GENERACIÓN FUNDADORA</p><h2>Tu sistema IA.<br/><em>Tu ventaja.</em></h2><p>La puerta de entrada a una nueva forma de trabajar en bienes raíces.</p></div><div className="offer"><span>INVERSIÓN FUNDADORA</span><strong>$999 <small>MXN</small></strong><p>Incluye workshop en vivo, materiales, prompts, metodología y piezas aplicables.</p><a href={whatsapp} target="_blank" rel="noreferrer">SOLICITAR INSCRIPCIÓN <b>↗</b></a></div></div></section>
  <footer className="shell wfooter"><b>LFMS BIENES RAÍCES</b><span>La IA no reemplaza al asesor. Reemplaza parte del trabajo que le quita tiempo.</span></footer>
</main>}
